version: '3.8'
services:
  mysql:
    image: mysql:8.0.22
    ports:
      - '3306:3306'
    volumes:
      - ./db_mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgres:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass

    ports:
      - '5432:5432'

    volumes:
      - ./db_postgres:/var/lib/postgresql

  node-app:
    build: ./gate-simulator
    image: node-app:Dockerfile.0
    ports:
      - '9999:9999'